# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernel.sysctl = { "vm.swappiness" = 1; };

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/5b7cad85-c8eb-47e4-8404-a318a23b1454";
      fsType = "btrfs";
      options = [ "subvol=@" "compress-force=zstd:3" "noatime" "discard=async" ];
    };

  boot.initrd.luks.devices."cryptlvm" = {
    device = "/dev/disk/by-uuid/6e0be3f0-43a7-41e5-8f19-ec00981f014a";
    allowDiscards = true;
  };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/7CC2-B106";
      fsType = "vfat";
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/5b7cad85-c8eb-47e4-8404-a318a23b1454";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress-force=zstd:3" "noatime" "discard=async" ];
    };

  fileSystems."/var/log" =
    {
      device = "/dev/disk/by-uuid/5b7cad85-c8eb-47e4-8404-a318a23b1454";
      fsType = "btrfs";
      options = [ "subvol=@log" "compress-force=zstd:3" "noatime" "discard=async" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/5b7cad85-c8eb-47e4-8404-a318a23b1454";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress-force=zstd:3" "noatime" "discard=async" ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/39448f34-d8c3-40e2-ab83-23d880489d62"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
