# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead. SIKE
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."cryptlvm" = {
    device = "/dev/disk/by-uuid/6e0be3f0-43a7-41e5-8f19-ec00981f014a";
    allowDiscards = true;
  };

  fileSystems = {
    "/boot" = {
      device = "/dev/disk/by-uuid/7CC2-B106";
      fsType = "vfat";
    };

    "/" = {
      device = "/dev/disk/by-uuid/5b7cad85-c8eb-47e4-8404-a318a23b1454";
      fsType = "btrfs";
      options = [ "subvol=@" "compress-force=zstd:3" "noatime" "discard=async" ];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/5b7cad85-c8eb-47e4-8404-a318a23b1454";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress-force=zstd:3" "noatime" "discard=async" ];
    };

    "/var/log" = {
      device = "/dev/disk/by-uuid/5b7cad85-c8eb-47e4-8404-a318a23b1454";
      fsType = "btrfs";
      options = [ "subvol=@log" "compress-force=zstd:3" "noatime" "discard=async" ];
    }; # FIXME: make nodatacow???

    "/nix" = {
      device = "/dev/disk/by-uuid/5b7cad85-c8eb-47e4-8404-a318a23b1454";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress-force=zstd:3" "noatime" "discard=async" ];
    };
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/39448f34-d8c3-40e2-ab83-23d880489d62"; }];

  networking = {
    useDHCP = false;
    interfaces = {
      enp3s0.useDHCP = true;
      wlp4s0.useDHCP = true;
    };
  };

  # powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.amd.updateMicrocode = true; # config.hardware.enableRedistributableFirmware
}
